from __future__ import annotations

from app.agents.base import BaseAgent
from app.common.clock import now_utc
from app.common.ids import new_id
from app.schemas import (
    ADMETSummary,
    AgentName,
    AgentResult,
    SourceType,
    StepStatus,
)
from app.tools.contracts import ToolRequest


class ADMETAgent(BaseAgent):
    agent_name = AgentName.ADMET

    def run(self, run, workspace) -> AgentResult:
        tool = self.get_tool("compute_admet")

        request = ToolRequest(payload={"compound": run.query})
        response = tool.execute(request)

        if response.status != "ok" or not response.results:
            return AgentResult(
                result_id=new_id("result"),
                run_id=run.run_id,
                agent_name=self.agent_name,
                status=StepStatus.FAILED,
                payload={},
                warnings=[],
                errors=response.errors or ["No ADMET result returned"],
                produced_at=now_utc(),
            )

        item = response.results[0]
        metadata = item.metadata

        admet_summary = ADMETSummary(
            admet_id=new_id("admet"),
            run_id=run.run_id,
            entity=run.query,
            solubility_bucket=metadata.get("solubility_bucket"),
            permeability_bucket=metadata.get("permeability_bucket"),
            cyp450_liability=metadata.get("cyp450_liability"),
            herg_risk=metadata.get("herg_risk"),
            method=metadata.get("method", "unknown"),
            source_type=SourceType.COMPUTED,
            confidence=float(metadata.get("confidence", 0.7)),
            notes=[f"Generated by {tool.name}"],
        )

        return AgentResult(
            result_id=new_id("result"),
            run_id=run.run_id,
            agent_name=self.agent_name,
            status=StepStatus.SUCCEEDED,
            payload={"admet_summary": admet_summary},
            warnings=[],
            errors=[],
            produced_at=now_utc(),
        )