from __future__ import annotations

from typing import Protocol

from app.schemas import AgentResult, ArtifactEnvelope, ReviewItem, Run, RunStep, RunWorkspace


class RunRepository(Protocol):
    def save_run(self, run: Run) -> None: ...
    def save_step(self, step: RunStep) -> None: ...
    def save_workspace(self, workspace: RunWorkspace) -> None: ...
    def save_agent_result(self, result: AgentResult) -> None: ...
    def save_artifact(self, artifact: ArtifactEnvelope) -> None: ...
    def save_review_item(self, review_item: ReviewItem) -> None: ...